apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1
  namespace: ingress-nginx
  labels:
    app: synthetic-service-mesh
    name: s1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s1
  template:
    metadata:
      labels:
        app: synthetic-service-mesh
        name: s1
        namespace: ingress-nginx
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "localhost/my-profile.json"
    spec:
      containers:
        - name: s1
          image: michelgokan/synthetic-service-mesh
          env:
            - name: NEXT_SERVICES_ADDRESSES
              value: "http://172.16.16.111:30553/s2/mem/1/1/1"
            - name: NAME
              value: "s1"
            - name: WORKERS_COUNT
                value: 8
          ports:
            - containerPort: 30005
      nodeSelector:
        kubernetes.io/hostname: node2
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: ingress-nginx
  labels:
    app: synthetic-service-mesh
    name: s1
spec:
  ports:
  - port: 30005
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    name: s1

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s1
  namespace: ingress-nginx
  annotations:
     nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
     nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
     nginx.org/client-max-body-size: "10000m" 
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - http:
        paths:
          - path: /s1
            backend:
              serviceName: s1
              servicePort: 30005
