apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2
  labels:
    app: sfc-stress
    name: s2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s2
  template:
    metadata:
      labels:
        app: sfc-stress
        name: s2
        namespace: ingress-nginx
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: my-profile.json
      containers:
        - name: s2
          image: michelgokan/sfc-stress
          env:
            #- name: NEXT_SERVICES_ADDRESSES
            #  value: "{\".*\": \"http://s3.default.svc.cluster.local:30005/net/1/0,http://s7.default.svc.cluster.local:30005/x/1/0\"}"
            - name: NAME
              value: "s2"
            - name: WORKERS_COUNT
              value: "100"
          ports:
            - containerPort: 30005
          readinessProbe:
            httpGet:
              path: /health
              port: 30005
            initialDelaySeconds: 5
            timeoutSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: s2
  labels:
    app: sfc-stress
    name: s2
spec:
  ports:
  - port: 30005
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    name: s2

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s2
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: web-ip
    cert-manager.io/issuer: letsencrypt-sfc-stress
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800000"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "1800000"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "1800000"
    nginx.org/client-max-body-size: "10000m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 1800000s;
      send_timeout 190000s;
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - host: 34.77.49.243.nip.io
#    - host: sfc-stress.perfsim.com
      http:
        paths:
          - pathType: Prefix
            path: /s2
            backend:
              service:
                name: s2
                port:
                  number: 30005
