apiVersion: apps/v1
kind: Deployment
metadata:
  name: s4
  namespace: ingress-nginx
  labels:
    app: sfc-stress
    name: s4
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s4
  template:
    metadata:
      labels:
        app: sfc-stress
        name: s4
        namespace: ingress-nginx
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "localhost/my-profile.json"
    spec:
      containers:
        - name: s4
          image: michelgokan/sfc-stress
          env:
            - name: NEXT_SERVICES_ADDRESSES
              value: "{\".*\": \"http://172.16.16.111:30553/s5/x/1/1\"}"
            - name: NAME
              value: "s4"
            - name: WORKERS_COUNT
              value: "100"
          ports:
            - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: s4
  namespace: ingress-nginx
  labels:
    app: sfc-stress
    name: s4
spec:
  ports:
    - port: 30005
      targetPort: 30005
      protocol: TCP
      name: http
  selector:
    name: s4

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s4
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800000"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "1800000"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "1800000"
    nginx.org/client-max-body-size: "10000m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 1800000s;
      send_timeout 190000s;
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - http:
        paths:
          - path: /s4
            backend:
              serviceName: s4
              servicePort: 30005