apiVersion: apps/v1
kind: Deployment
metadata:
  name: s5
  namespace: ingress-nginx
  labels:
    app: sfc-stress
    name: s5
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s5
  template:
    metadata:
      labels:
        app: sfc-stress
        namespace: ingress-nginx
        name: s5
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "localhost/my-profile.json"
    spec:
      containers:
        - name: s5
          image: michelgokan/sfc-stress
          env:
            - name: NEXT_SERVICES_ADDRESSES
              value: "http://172.16.16.111:30553/s4/blkio/1/1/0/0"
            - name: NAME
              value: "s5"
            - name: WORKERS_COUNT
              value: "100"
          ports:
            - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: s5
  namespace: ingress-nginx
  labels:
    app: sfc-stress
    name: s5
spec:
  ports:
  - port: 30009
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    name: s5

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s5
  namespace: ingress-nginx
  annotations:
     nginx.ingress.kubernetes.io/proxy-send-timeout: "18000"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "18000"
     nginx.ingress.kubernetes.io/proxy-connect-timeout: "18000"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
     nginx.org/client-max-body-size: "10000m" 
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - http:
        paths:
          - path: /s5
            backend:
              serviceName: s5
              servicePort: 30005
