apiVersion: apps/v1
kind: Deployment
metadata:
  name: s7
  labels:
    app: sfc-stress
    name: s7
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s7
  template:
    metadata:
      labels:
        app: sfc-stress
        name: s7
        namespace: ingress-nginx
    spec:
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: my-profile.json
      containers:
        - name: s7
          image: michelgokan/sfc-stress
          env:
            - name: NEXT_SERVICES_ADDRESSES
              value: "http://sfc-stress.dev/s8/blkio"
            - name: NAME
              value: "s7"
            - name: WORKERS_COUNT
              value: "100"
          ports:
            - containerPort: 30005
          readinessProbe:
            httpGet:
              path: /health
              port: 30005
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: s7
  labels:
    app: sfc-stress
    name: s7
spec:
  ports:
  - port: 30005
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    name: s7

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s7
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: web-ip
    cert-manager.io/issuer: letsencrypt-sfc-stress
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800000"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "1800000"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "1800000"
    nginx.org/client-max-body-size: "10000m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 1800000s;
      send_timeout 190000s;
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - host: 34.77.49.243.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /s7
            backend:
              service:
                name: s7
                port:
                  number: 30005
